export const dataPlaca = [
    {week: 0,
    data: [  
      { role: 'Líder', name: 'Martina', result: '-' },
      { role: 'Nominado', name: 'Walter', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Marcos', result: '17,96% (Entre 3)' },
      { role: 'Nominado', name: 'Agustín', result: '40,66% (Entre 2)' },
      { role: 'Nominado', name: 'Tomás', result: 'Eliminado (59,40%)' },
    ],
    },
    {
      week: 1,
      data: [
      { role: 'Líder', name: 'Maximiliano', result: '-' },
      { role: 'Nominado', name: 'Walter', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Nacho', result: '3,03%' },
      { role: 'Nominado', name: 'Juan', result: '39,55%' },
      { role: 'Nominado', name: 'Martina', result: 'Eliminado (57,42%)' },
    ],
    },
    {
      week: 2,
      data: [
      { role: 'Líder', name: 'Romina', result: '-' },
      { role: 'Nominado', name: 'Daniela', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Walter', result: '6,72% (Entre 4)' },
      { role: 'Nominado', name: 'Agustín', result: '9,93% (Entre 3)' },
      { role: 'Nominado', name: 'Juan', result: '39,93% (Entre 2)' },
      { role: 'Nominado', name: 'Mora', result: 'Eliminado (60,07%)' },
    ],
    },
    {
      week: 3,
      data: [
      { role: 'Líder', name: 'Lucila', result: '-' },
      { role: 'Nominado', name: 'Agustín', result: '0,78% (Entre 5)' },
      { role: 'Nominado', name: 'Nacho', result: '3,27% (Entre 4)' },
      { role: 'Nominado', name: 'Daniela', result: '6,53% (Entre 3)' },
      { role: 'Nominado', name: 'Walter', result: '11,86% (Entre 2)' },
      { role: 'Nominado', name: 'Juan', result: 'Eliminado (88,14%)' },
    ],
    },
    {
      week: 4,
      data: [
      { role: 'Líder', name: 'Alexis', result: '-' },
      { role: 'Líder', name: 'Nacho', result: '-' },
      { role: 'Nominado', name: 'María Laura', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Walter', result: '4,45% (Entre 3)' },
      { role: 'Nominado', name: 'Juliana', result: '34,62% (Entre 2)' },
      { role: 'Nominado', name: 'Lucila', result: 'Eliminado (65,38%)' },
    ],
    },
    {
      week: 5,
      data: [
      { role: 'Líder', name: 'Thiago', result: '-' },
      { role: 'Nominado', name: 'Romina', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Agustín', result: '5,70% (Entre 4)' },
      { role: 'Nominado', name: 'Nacho', result: '8,86% (Entre 3)' },
      { role: 'Nominado', name: 'María Laura', result: '42,33% (Entre 2)' },
      { role: 'Nominado', name: 'Juliana', result: 'Eliminado (57,67%)' },
    ],
    },
    {
      week: 6,
      data: [
      { role: 'Líder', name: 'Romina', result: '-' },
      { role: 'Nominado', name: 'Constanza', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Walter', result: '3,17% (Entre 4)' },
      { role: 'Nominado', name: 'Nacho', result: '24,01% (Entre 3)' },
      { role: 'Nominado', name: 'Daniela', result: '47,20% (Entre 2)' },
      { role: 'Nominado', name: 'María Laura', result: 'Eliminado (52,80%)' },
    ],
    },
    {
      week: 7,
      data: [
      { role: 'Líder', name: 'Thiago', result: '-' },
      { role: 'Nominado', name: 'Maximiliano', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Marcos', result: '1,08% (Entre 5)' },
      { role: 'Nominado', name: 'Julieta', result: '5,78% (Entre 4)' },
      { role: 'Nominado', name: 'Romina', result: '6,42% (Entre 3)' },
      { role: 'Nominado', name: 'Nacho', result: '23,53% (Entre 2)' },
      { role: 'Nominado', name: 'Agustín', result: 'Eliminado (76,47%)' },
    ],
    },
    {
      week: 8,
      data: [
      { role: 'Líder', name: 'Thiago', result: '-' },
      { role: 'Nominado', name: 'Alexis', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Romina', result: '7,97% (Entre 3)' },
      { role: 'Nominado', name: 'Julieta', result: '26,71% (Entre 2)' },
      { role: 'Nominado', name: 'Daniela', result: 'Eliminado (73,29%)' },
    ],
    },
    {
      week: 9,
      data: [
      { role: 'Líder', name: 'Alexis', result: '-' },
      { role: 'Salvado', name: 'Juliana', result: '3 votos' },
      { role: 'Salvado', name: 'Daniela', result: '40,98% (Entre 8)' },
      { role: 'Salvado', name: 'Agustín', result: '47,15% (Entre 3)' },
      { role: 'Salvado', name: 'Lucila', result: '68,76% (Entre 2)' },
      { role: 'En repechaje', name: 'Mora', result: 'Eliminado (31,24%)' },
      { role: 'En repechaje', name: 'Martina', result: 'Cortado (7,85%)' },
      { role: 'En repechaje', name: 'Tomás', result: 'Cortado (5,64%)' },
      { role: 'En repechaje', name: 'Juan', result: 'Cortado (2,89%)' },
      { role: 'En repechaje', name: 'María Laura', result: 'Cortado (2,19%)' },
    ],
    },
    {
      week: 10,
      data: [
      { role: 'Líder', name: 'Thiago', result: '-' },
      { role: 'Nominado', name: 'Camila', result: '0,72% (Entre 5)' },
      { role: 'Nominado', name: 'Walter', result: '5,55% (Entre 4)' },
      { role: 'Nominado', name: 'Daniela', result: '13,12% (Entre 3)' },
      { role: 'Nominado', name: 'Ariel', result: '32,65% (Entre 2)' },
      { role: 'Nominado', name: 'Constanza', result: 'Eliminado (67,35%)' },
    ],
    },
    {
      week: 11,
      data: [
      { role: 'Líder', name: 'Nacho', result: '-' },
      { role: 'Nominado', name: 'Lucila', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Agustín', result: '15,80% (Entre 3)' },
      { role: 'Nominado', name: 'Ariel', result: '43,81% (Entre 2)' },
      { role: 'Nominado', name: 'Alexis', result: 'Eliminado (56,19%)' },
    ],
    },
    {
      week: 12,
      data: [
      { role: 'Líder', name: 'Maximiliano', result: '-' },
      { role: 'Nominado', name: 'Nacho', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Camila', result: '7,82% (Entre 3)' },
      { role: 'Nominado', name: 'Agustín', result: '47,10% (Entre 2)' },
      { role: 'Nominado', name: 'Thiago', result: 'Eliminado (52,90%)' },
    ],
    },
    {
      week: 13,
      data: [
      { role: 'Líder', name: 'Marcos', result: '-' },
      { role: 'Nominado', name: 'Agustín', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Nacho', result: '15,02% (Entre 3)' },
      { role: 'Nominado', name: 'Ariel', result: '47,98% (Entre 2)' },
      { role: 'Nominado', name: 'Maximiliano', result: 'Eliminado (52,02%)' },
    ],
    },
    {
      week: 14,
      data: [
      { role: 'Líder', name: 'Marcos', result: '-' },
      { role: 'Líder', name: 'Romina', result: '-' },
      { role: 'Nominado', name: 'Ariel', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Lucila', result: '3,38% (Entre 3)' },
      { role: 'Nominado', name: 'Daniela', result: '49,19% (Entre 2)' },
      { role: 'Nominado', name: 'Agustín', result: 'Eliminado (50,81%)' },
    ],
    },
    {
      week: 15,
      data: [
      { role: 'Líder', name: 'Camila', result: '-' },
      { role: 'Nominado', name: 'Walter', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Marcos', result: '2% (Entre 4)' },
      { role: 'Nominado', name: 'Nacho', result: '14,63% (Entre 3)' },
      { role: 'Nominado', name: 'Julieta', result: '44,79% (Entre 2)' },
      { role: 'Nominado', name: 'Ariel', result: 'Eliminado (55,21%)' },
    ],
    },
    {
      week: 16,
      data: [
      { role: 'Líder', name: 'Julieta', result: '-' },
      { role: 'Nominado', name: 'Camila', result: 'Salvado por el líder' },
      { role: 'Nominado', name: 'Lucila', result: '5,61% (Entre 3)' },
      { role: 'Nominado', name: 'Romina', result: '47,17% (Entre 2)' },
      { role: 'Nominado', name: 'Walter', result: 'Eliminado (52,83%)' },
    ],
    },  
    ];