import React, { useState, useEffect } from 'react';
import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const useData = () => {
    const [data, setData] = useState([
/*SEMANA 1*/
[
    ['Agustín', 'María Laura', 'Juan'],
    ['Alexis', 'Walter', 'Agustín'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Nacho', 'Juan'],
    ['Daniela', 'Tomás', 'Walter'],
    ['Juan', 'Marcos', 'Agustín'],
    ['Juliana', 'Marcos', 'Agustín'],
    ['Julieta', 'Juan', 'Tomás'],
    ['Lucila', 'Tomás', 'Agustín'],
    ['Marcos', 'Tomás', 'Nacho'],
    ['María Laura', 'Walter', 'Tomás'],
    ['Martina', 'Lucila', 'Marcos'],
    ['Maximiliano', 'Walter', 'Romina'],
    ['Mora', 'Agustín', 'Walter'],
    ['Nacho', 'Walter', 'Marcos'],
    ['Romina', 'Tomás', 'Nacho'],
    ['Thiago', 'Walter', 'Agustín'],
    ['Tomás', 'Constanza', 'Marcos'],
    ['Walter', 'Tomás', 'Juan'],
    ],
    /*SEMANA 2*/
    [
    ['Agustín', 'Juan', 'Mora'],
    ['Alexis', 'Nacho', 'Martina'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Nacho', 'Walter'],
    ['Daniela', 'Juan', 'Walter'],
    ['Juan', 'Constanza', 'Alexis'],
    ['Juliana', 'Martina', 'Juan'],
    ['Julieta', 'Martina', 'Juan'],
    ['Lucila', 'Nacho', 'Walter'],
    ['Marcos', 'Nacho', 'Juan'],
    ['María Laura', 'Juan', 'Walter'],
    ['Martina', 'Alexis', 'Constanza'],
    ['Maximiliano', 'Martina', 'Nacho'],
    ['Mora', 'Nacho', 'Alexis'],
    ['Nacho', 'Alexis', 'Constanza'],
    ['Romina', 'Martina', 'Nacho'],
    ['Thiago', 'Martina', 'Juan'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Juan', 'Nacho'],
    ],
    
    /*SEMANA 3*/
    [
    ['Agustín', 'Mora', 'Daniela'],
    ['Alexis', 'Daniela', 'Mora'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Lucila', 'Mora'],
    ['Daniela', 'Walter', 'Agustín'],
    ['Juan', 'Agustín', 'Mora'],
    ['Juliana', 'Daniela', 'Juan'],
    ['Julieta', 'Juan', 'Agustín'],
    ['Lucila', 'Marcos', 'Agustín'],
    ['Marcos', 'Juan', 'Nacho'],
    ['María Laura', 'Agustín', 'Walter'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Agustín', 'Daniela'],
    ['Mora', 'Agustín', 'Walter'],
    ['Nacho', 'Agustín', 'Daniela'],
    ['Romina', 'Agustín', 'Nacho'],
    ['Thiago', 'Agustín', 'Walter'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Agustín', 'Lucila'],
    ],
    /*SEMANA 4*/
    [
    ['Agustín', 'Daniela', 'María Laura'],
    ['Alexis', 'Daniela', 'Nacho'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Marcos', 'Agustín'],
    ['Daniela', 'Nacho', 'Juan'],
    ['Juan', 'Julieta', 'Constanza'],
    ['Juliana', 'Julieta', 'Constanza'],
    ['Julieta', 'Juan', 'Nacho'],
    ['Lucila', 'Julieta', 'Constanza'],
    ['Marcos', 'María Laura', 'Juan'],
    ['María Laura', 'Constanza', 'Julieta'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Daniela', 'Agustín'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Daniela', 'Julieta'],
    ['Romina', 'Agustín', 'Nacho'],
    ['Thiago', 'Juan', 'Agustín'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Juan', 'María Laura'],
    ],
    /*SEMANA 5*/
    [
    ['Agustín', 'María Laura', 'Lucila'],
    ['Alexis', 'Constanza', 'María Laura'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Lucila', 'María Laura'],
    ['Daniela', 'Maximiliano', 'Juliana'],
    ['Juan', '4° eliminado'],
    ['Juliana', 'Romina', 'Julieta'],
    ['Julieta', 'Lucila', 'María Laura'],
    ['Lucila', 'Walter', 'Marcos'],
    ['Marcos', 'Lucila', 'María Laura'],
    ['María Laura', 'Marcos', 'Walter'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Julieta', 'María Laura'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Romina', 'Walter'],
    ['Romina', 'Juliana', 'Maximiliano'],
    ['Thiago', 'Juliana', 'Lucila'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Lucila', 'María Laura'],
    ],
    /*SEMANA 6*/
    [
    ['Agustín', 'Romina', 'Julieta'],
    ['Alexis', 'Romina', 'Voto anulado'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Agustín', 'Voto anulado'],
    ['Daniela', 'Nacho', 'María Laura'],
    ['Juan', '4° eliminado'],
    ['Juliana', 'Nacho', 'Walter'],
    ['Julieta', 'Juliana', 'María Laura'],
    ['Lucila', '5° eliminada'],
    ['Marcos', 'Nacho', 'María Laura'],
    ['María Laura', 'Constanza', 'Juliana'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Walter', 'Agustín'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Marcos', 'Juliana'],
    ['Romina', 'Juliana', 'Agustín'],
    ['Thiago', 'María Laura', 'Juliana'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Juliana', 'Nacho'],
    ],  
    /*SEMANA 7*/
    [
    ['Agustín', 'Daniela', 'María Laura'],
    ['Alexis', 'Nacho', 'María Laura'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Nacho', 'María Laura'],
    ['Daniela', 'Nacho', 'Walter'],
    ['Juan', '4° eliminado'],
    ['Juliana', '6° eliminada'],
    ['Julieta', 'Nacho', 'Maximiliano'],
    ['Lucila', '5° eliminada'],
    ['Marcos', 'María Laura', 'Nacho'],
    ['María Laura', 'Constanza', 'Daniela'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Romina', 'Walter'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Constanza', 'Daniela'],
    ['Romina', 'Agustín', 'Nacho'],
    ['Thiago', 'Walter', 'Maximiliano'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Daniela', 'Constanza'],
    ],
    /*SEMANA 8*/
    [
    ['Agustín', 'Romina', 'Nacho'],
    ['Alexis', 'Julieta', 'Marcos'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Marcos', 'Julieta'],
    ['Daniela', 'Maximiliano', 'Agustín'],
    ['Juan', '4° eliminado'],
    ['Juliana', '6° eliminada'],
    ['Julieta', 'Maximiliano', 'Agustín'],
    ['Lucila', '5° eliminada'],
    ['Marcos', 'Nacho', 'Daniela'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Romina', 'Walter'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Romina', 'Constanza'],
    ['Romina', 'Agustín', 'Maximiliano'],
    ['Thiago', 'Romina', 'Walter'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Maximiliano', 'Agustín'],
    ],
    /*SEMANA 9*/
    [
    ['Agustín', 'Romina', 'Nacho'],
    ['Alexis', 'Julieta', 'Marcos'],
    ['Ariel', 'No estaba'],
    ['Camila', 'No estaba'],
    ['Constanza', 'Julieta', 'Daniela'],
    ['Daniela', 'Maximiliano', 'Agustín'],
    ['Juan', '4° eliminado'],
    ['Juliana', '6° eliminada'],
    ['Julieta', 'Maximiliano', 'Agustín'],
    ['Lucila', '5° eliminada'],
    ['Marcos', 'Nacho', 'Daniela'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Romina', 'Walter'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Romina', 'Constanza'],
    ['Romina', 'Agustín', 'Maximiliano'],
    ['Thiago', 'Romina', 'Walter'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Maximiliano', 'Agustín'],
    ],
    /*SEMANA 10*/
    [
    ['Agustín', '8° eliminado'],
    ['Alexis', 'Juliana'],
    ['Ariel', 'No vota'],
    ['Camila', 'No vota'],
    ['Constanza', 'Voto anulado'],
    ['Daniela', '9° eliminada'],
    ['Juan', '4° eliminado'],
    ['Juliana', '6° eliminada'],
    ['Julieta', 'Daniela'],
    ['Lucila', '5° eliminada'],
    ['Marcos', 'Agustín'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Juliana'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'María Laura'],
    ['Romina', 'Daniela'],
    ['Thiago', 'Daniela'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'María Laura'],
    ],
    /*SEMANA 11*/
    [
    ['Agustín', 'Daniela', 'Alexis'],
    ['Alexis', 'Daniela', 'Agustín'],
    ['Ariel', 'Walter', 'Nacho'],
    ['Camila', 'Voto anulado'],
    ['Constanza', 'Walter', 'Daniela'],
    ['Daniela', 'Constanza', 'Thiago'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Constanza', 'Agustín'],
    ['Lucila', 'Alexis', 'Ariel'],
    ['Marcos', 'Nacho', 'Ariel'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Daniela', 'Walter'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Constanza', 'Ariel'],
    ['Romina', 'Agustín', 'Constanza'],
    ['Thiago', 'Constanza', 'Alexis'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Ariel', 'Constanza'],
    ],
    /*SEMANA 12*/
    [
    ['Agustín', 'Alexis', 'Lucila'],
    ['Alexis', 'Daniela', 'Camila'],
    ['Ariel', 'Agustín', 'Marcos'],
    ['Camila', 'Lucila', 'Agustín'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Alexis', 'Maximiliano'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Agustín', 'Alexis'],
    ['Lucila', 'Maximiliano', 'Alexis'],
    ['Marcos', 'Lucila', 'Ariel'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Daniela', 'Ariel'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Camila', 'Agustín'],
    ['Romina', 'Agustín', 'Ariel'],
    ['Thiago', 'Alexis', 'Ariel'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Ariel', 'Alexis'],
    ],
    /*SEMANA 13*/
    [
    ['Agustín', 'Camila', 'Thiago'],
    ['Alexis', '11° eliminado'],
    ['Ariel', 'Nacho', 'Walter'],
    ['Camila', 'Thiago', 'Nacho'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Agustín', 'Thiago'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Camila', 'Thiago'],
    ['Lucila', 'Thiago', 'Camila'],
    ['Marcos', 'Lucila', 'Ariel'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Walter', 'Agustín'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Camila', 'Marcos'],
    ['Romina', 'Agustín', 'Nacho'],
    ['Thiago', 'Camila', 'Ariel'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Ariel', 'Thiago'],
    ],
    /*SEMANA 14*/
    [
    ['Agustín', 'Ariel', 'Maximiliano'],
    ['Alexis', '11° eliminado'],
    ['Ariel', 'Julieta', 'Romina'],
    ['Camila', 'Lucila', 'Agustín'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Maximiliano', 'Ariel'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Maximiliano', 'Ariel'],
    ['Lucila', 'Ariel', 'Maximiliano'],
    ['Marcos', 'Nacho', 'Ariel'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', 'Daniela', 'Ariel'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Ariel', 'Agustín'],
    ['Romina', 'Nacho', 'Agustín'],
    ['Thiago', '12° eliminado'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Ariel', 'Maximiliano'],
    ],
    /*SEMANA 15*/
    [
    ['Agustín', 'Daniela', 'Julieta'],
    ['Alexis', '11° eliminado'],
    ['Ariel', 'Walter', 'Julieta'],
    ['Camila', 'Lucila', 'Nacho'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Agustín', 'Ariel'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Agustín', 'Ariel'],
    ['Lucila', 'Camila', 'Ariel'],
    ['Marcos', 'Lucila', 'Ariel'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', '13° eliminado'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Daniela', 'Camila'],
    ['Romina', 'Nacho', 'Agustín'],
    ['Thiago', '12° eliminado'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Ariel', 'Lucila'],
    ],
    /*SEMANA 16*/
    [
    ['Agustín', '14° eliminado'],
    ['Alexis', '11° eliminado'],
    ['Ariel', 'Julieta', 'Romina'],
    ['Camila', 'Nacho', 'Lucila'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Ariel', 'Walter'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Ariel', 'Walter'],
    ['Lucila', 'Walter', 'Daniela'],
    ['Marcos', 'Nacho', 'Ariel'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', '13° eliminado'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Marcos', 'Julieta'],
    ['Romina', 'Nacho', 'Ariel'],
    ['Thiago', '12° eliminado'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Ariel', 'Marcos'],
    ],
    /*SEMANA 17*/
    [
    ['Agustín', '14° eliminado'],
    ['Alexis', '11° eliminado'],
    ['Ariel', '15° eliminado'],
    ['Camila', 'Lucila', 'Romina'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Walter', 'Camila'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Lucila', 'Walter'],
    ['Lucila', 'Camila', 'Walter'],
    ['Marcos', 'Lucila', 'Daniela'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', '13° eliminado'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Camila', 'Walter'],
    ['Romina', 'Camila', 'Walter'],
    ['Thiago', '12° eliminado'],
    ['Tomás', '1° eliminado'],
    ['Walter', 'Romina', 'Lucila'],
    ],
    /*SEMANA 18*/
    [
    ['Agustín', '14° eliminado'],
    ['Alexis', '11° eliminado'],
    ['Ariel', '15° eliminado'],
    ['Camila', 'Lucila', 'Daniela'],
    ['Constanza', '10° eliminada'],
    ['Daniela', 'Nacho', 'Lucila'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', 'Camila'],
    ['Lucila', 'Daniela', 'Julieta'],
    ['Marcos', 'Lucila', 'Daniela'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', '13° eliminado'],
    ['Mora', '3° eliminada'],
    ['Nacho', 'Julieta', 'Daniela'],
    ['Romina', 'Nacho', 'Marcos'],
    ['Thiago', '12° eliminado'],
    ['Tomás', '1° eliminado'],
    ['Walter', '16° eliminado'],
    ],
    /*SEMANA 19*/
    [
    ['Agustín', '14° eliminado'],
    ['Alexis', '11° eliminado'],
    ['Ariel', '15° eliminado'],
    ['Camila', '-', '-'],
    ['Constanza', '10° eliminada'],
    ['Daniela', '17° eliminada'],
    ['Juan', '4° eliminado'],
    ['Juliana', '1° expulsada'],
    ['Julieta', '-', '-'],
    ['Lucila', '-', '-'],
    ['Marcos', '-', '-'],
    ['María Laura', '7° eliminada'],
    ['Martina', '2° eliminada'],
    ['Maximiliano', '13° eliminado'],
    ['Mora', '3° eliminada'],
    ['Nacho', '-', '-'],
    ['Romina', '-', '-'],
    ['Thiago', '12° eliminado'],
    ['Tomás', '1° eliminado'],
    ['Walter', '16° eliminado'],
    ],
    ]);
    data[1][15].espontanea = true; /*semana 2*/
    data[1][6].anulado = true; /*semana 2*/
    data[1][12].anulado = true; /*semana 2*/
    data[1][15].anulado = true; /*semana 2*/
    data[2][4].espontanea = true; /*semana 3*/
    data[3][9].espontanea = true; /*semana 4*/
    data[3][6].anulado = true; /*semana 4*/
    data[3][7].anulado = true; /*semana 4*/
    data[3][9].anulado = true; /*semana 4*/
    data[4][9].espontanea = true; /*semana 5*/
    data[4][1].anulado = true; /*semana 5*/
    data[4][4].anulado = true; /*semana 5*/
    data[5][5].espontanea = true; /*semana 6*/
    data[6][13].espontanea = true; /*semana 7*/
    data[6][13].anulado1 = true; /*semana 7*/ /*solo anulado el primer voto*/
    data[7][8].espontanea = true; /*semana 8*/
    data[8][4].espontanea = true; /*semana 9*/
    data[10][5].espontanea = true; /*semana 11*/
    data[10][5].anulado2 = true; /*semana 11*/ /*solo anulado el segundo voto*/
    data[11][5].espontanea = true; /*semana 12*/
    data[12][3].espontanea = true; /*semana 13*/
    data[13][5].espontanea = true; /*semana 14*/
    data[14][8].espontanea = true; /*semana 15*/
    data[16][15].espontanea = true; /*semana 17*/
    data[16][16].anulado2 = true; /*semana 17*/ /*solo anulado el segundo voto*/
    data[17][8].fulminante = true; /*semana 18*/
    return [data, setData];
  };